# Install requirements and run pytest
# TODO: Build app and check?
image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python -m pytest --cov=bad_site_checker .
          - pycodestyle --max-line-length=119 bad_site_checker
