version: "3"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"

  db:
    env_file:
      - .env
    image: mysql/mysql-server:8.0.23
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
